services:
  postgres:
    container_name: postgres
    image: postgres:16
    environment:
      POSTGRES_DB: confluence
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    networks:
      - confluence-net

  confluence_vulnerable:
    depends_on:
      - postgres
    container_name: confluence
    image: atlassian/confluence:8.4.1
    ports:
      - '8090:8090'
      - '8091:8091'
    networks:
      - confluence-net
    environment:
      ATL_DB_TYPE: postgresql
      ATL_DB_DRIVER: org.postgresql.Driver
      ATL_JDBC_USER: postgres
      ATL_JDBC_PASSWORD: postgres
      ATL_JDBC_URL: jdbc:postgresql://postgres:5432/confluence

#  confluence_safe:
#    depends_on:
#      - postgres
#    container_name: confluence
#    image: atlassian/confluence:8.6.0
#    ports:
#      - '8090:8090'
#      - '8091:8091'
#    networks:
#      - confluence-net
#    environment:
#      ATL_DB_TYPE: postgresql
#      ATL_DB_DRIVER: org.postgresql.Driver
#      ATL_JDBC_USER: postgres
#      ATL_JDBC_PASSWORD: postgres
#      ATL_JDBC_URL: jdbc:postgresql://postgres:5432/confluence

networks:
  confluence-net:
    driver: bridge
